spring:
  application:
    name: text-to-sql
  threading:
    virtual:
      enabled: true
  ai:
    openai:
      api-key: ${OPENAI_API_KEY:demo}
      chat:
        options:
          model: gpt-4o-mini
          temperature: 0.0
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres